-- 2024-02-27wiscourper    inbody770
ALTER TABLE `ydy_equipment_result_extend`
ADD COLUMN `k91` varchar(64) NOT NULL DEFAULT '' AFTER `k90`,
ADD COLUMN `k92` varchar(64) NOT NULL DEFAULT '' AFTER `k91`,
ADD COLUMN `k93` varchar(64) NOT NULL DEFAULT '' AFTER `k92`,
ADD COLUMN `k94` varchar(64) NOT NULL DEFAULT '' AFTER `k93`,
ADD COLUMN `k95` varchar(64) NOT NULL DEFAULT '' AFTER `k94`,
ADD COLUMN `k96` varchar(64) NOT NULL DEFAULT '' AFTER `k95`,
ADD COLUMN `k97` varchar(64) NOT NULL DEFAULT '' AFTER `k96`,
ADD COLUMN `k98` varchar(64) NOT NULL DEFAULT '' AFTER `k97`,
ADD COLUMN `k99` varchar(64) NOT NULL DEFAULT '' AFTER `k98`,
ADD COLUMN `k100` varchar(64) NOT NULL DEFAULT '' AFTER `k99`,

ADD COLUMN `k101` varchar(64) NOT NULL DEFAULT '' AFTER `k100`,
ADD COLUMN `k102` varchar(64) NOT NULL DEFAULT '' AFTER `k101`,
ADD COLUMN `k103` varchar(64) NOT NULL DEFAULT '' AFTER `k102`,
ADD COLUMN `k104` varchar(64) NOT NULL DEFAULT '' AFTER `k103`,
ADD COLUMN `k105` varchar(64) NOT NULL DEFAULT '' AFTER `k104`,
ADD COLUMN `k106` varchar(64) NOT NULL DEFAULT '' AFTER `k105`,
ADD COLUMN `k107` varchar(64) NOT NULL DEFAULT '' AFTER `k106`,
ADD COLUMN `k108` varchar(64) NOT NULL DEFAULT '' AFTER `k107`,
ADD COLUMN `k109` varchar(64) NOT NULL DEFAULT '' AFTER `k108`,
ADD COLUMN `k110` varchar(64) NOT NULL DEFAULT '' AFTER `k109`,

ADD COLUMN `k111` varchar(64) NOT NULL DEFAULT '' AFTER `k110`,
ADD COLUMN `k112` varchar(64) NOT NULL DEFAULT '' AFTER `k111`,
ADD COLUMN `k113` varchar(64) NOT NULL DEFAULT '' AFTER `k112`,
ADD COLUMN `k114` varchar(64) NOT NULL DEFAULT '' AFTER `k113`,
ADD COLUMN `k115` varchar(64) NOT NULL DEFAULT '' AFTER `k114`,
ADD COLUMN `k116` varchar(64) NOT NULL DEFAULT '' AFTER `k115`,
ADD COLUMN `k117` varchar(64) NOT NULL DEFAULT '' AFTER `k116`,
ADD COLUMN `k118` varchar(64) NOT NULL DEFAULT '' AFTER `k117`,
ADD COLUMN `k119` varchar(64) NOT NULL DEFAULT '' AFTER `k118`,
ADD COLUMN `k120` varchar(64) NOT NULL DEFAULT '' AFTER `k119`,

ADD COLUMN `k121` varchar(64) NOT NULL DEFAULT '' AFTER `k120`,
ADD COLUMN `k122` varchar(64) NOT NULL DEFAULT '' AFTER `k121`,
ADD COLUMN `k123` varchar(64) NOT NULL DEFAULT '' AFTER `k122`,
ADD COLUMN `k124` varchar(64) NOT NULL DEFAULT '' AFTER `k123`,
ADD COLUMN `k125` varchar(64) NOT NULL DEFAULT '' AFTER `k124`,
ADD COLUMN `k126` varchar(64) NOT NULL DEFAULT '' AFTER `k125`,
ADD COLUMN `k127` varchar(64) NOT NULL DEFAULT '' AFTER `k126`,
ADD COLUMN `k128` varchar(64) NOT NULL DEFAULT '' AFTER `k127`,
ADD COLUMN `k129` varchar(64) NOT NULL DEFAULT '' AFTER `k128`,
ADD COLUMN `k130` varchar(64) NOT NULL DEFAULT '' AFTER `k129`,

ADD COLUMN `k131` varchar(64) NOT NULL DEFAULT '' AFTER `k130`,
ADD COLUMN `k132` varchar(64) NOT NULL DEFAULT '' AFTER `k131`,
ADD COLUMN `k133` varchar(64) NOT NULL DEFAULT '' AFTER `k132`,
ADD COLUMN `k134` varchar(64) NOT NULL DEFAULT '' AFTER `k133`,
ADD COLUMN `k135` varchar(64) NOT NULL DEFAULT '' AFTER `k134`,
ADD COLUMN `k136` varchar(64) NOT NULL DEFAULT '' AFTER `k135`,
ADD COLUMN `k137` varchar(64) NOT NULL DEFAULT '' AFTER `k136`,
ADD COLUMN `k138` varchar(64) NOT NULL DEFAULT '' AFTER `k137`,
ADD COLUMN `k139` varchar(64) NOT NULL DEFAULT '' AFTER `k138`,
ADD COLUMN `k140` varchar(64) NOT NULL DEFAULT '' AFTER `k139`,

ADD COLUMN `k141` varchar(64) NOT NULL DEFAULT '' AFTER `k140`,
ADD COLUMN `k142` varchar(64) NOT NULL DEFAULT '' AFTER `k141`,
ADD COLUMN `k143` varchar(64) NOT NULL DEFAULT '' AFTER `k142`,
ADD COLUMN `k144` varchar(64) NOT NULL DEFAULT '' AFTER `k143`,
ADD COLUMN `k145` varchar(64) NOT NULL DEFAULT '' AFTER `k144`,
ADD COLUMN `k146` varchar(64) NOT NULL DEFAULT '' AFTER `k145`,
ADD COLUMN `k147` varchar(64) NOT NULL DEFAULT '' AFTER `k146`,
ADD COLUMN `k148` varchar(64) NOT NULL DEFAULT '' AFTER `k147`,
ADD COLUMN `k149` varchar(64) NOT NULL DEFAULT '' AFTER `k148`,
ADD COLUMN `k150` varchar(64) NOT NULL DEFAULT '' AFTER `k149`,

ADD COLUMN `k151` varchar(64) NOT NULL DEFAULT '' AFTER `k150`,
ADD COLUMN `k152` varchar(64) NOT NULL DEFAULT '' AFTER `k151`,
ADD COLUMN `k153` varchar(64) NOT NULL DEFAULT '' AFTER `k152`,
ADD COLUMN `k154` varchar(64) NOT NULL DEFAULT '' AFTER `k153`,
ADD COLUMN `k155` varchar(64) NOT NULL DEFAULT '' AFTER `k154`,
ADD COLUMN `k156` varchar(64) NOT NULL DEFAULT '' AFTER `k155`,
ADD COLUMN `k157` varchar(64) NOT NULL DEFAULT '' AFTER `k156`,
ADD COLUMN `k158` varchar(64) NOT NULL DEFAULT '' AFTER `k157`,
ADD COLUMN `k159` varchar(64) NOT NULL DEFAULT '' AFTER `k158`,
ADD COLUMN `k160` varchar(64) NOT NULL DEFAULT '' AFTER `k159`,

ADD COLUMN `k161` varchar(64) NOT NULL DEFAULT '' AFTER `k160`,
ADD COLUMN `k162` varchar(64) NOT NULL DEFAULT '' AFTER `k161`,
ADD COLUMN `k163` varchar(64) NOT NULL DEFAULT '' AFTER `k162`,
ADD COLUMN `k164` varchar(64) NOT NULL DEFAULT '' AFTER `k163`,
ADD COLUMN `k165` varchar(64) NOT NULL DEFAULT '' AFTER `k164`,
ADD COLUMN `k166` varchar(64) NOT NULL DEFAULT '' AFTER `k165`,
ADD COLUMN `k167` varchar(64) NOT NULL DEFAULT '' AFTER `k166`,
ADD COLUMN `k168` varchar(64) NOT NULL DEFAULT '' AFTER `k167`,
ADD COLUMN `k169` varchar(64) NOT NULL DEFAULT '' AFTER `k168`,
ADD COLUMN `k170` varchar(64) NOT NULL DEFAULT '' AFTER `k169`,

ADD COLUMN `k171` varchar(64) NOT NULL DEFAULT '' AFTER `k170`,
ADD COLUMN `k172` varchar(64) NOT NULL DEFAULT '' AFTER `k171`,
ADD COLUMN `k173` varchar(64) NOT NULL DEFAULT '' AFTER `k172`,
ADD COLUMN `k174` varchar(64) NOT NULL DEFAULT '' AFTER `k173`,
ADD COLUMN `k175` varchar(64) NOT NULL DEFAULT '' AFTER `k174`,
ADD COLUMN `k176` varchar(64) NOT NULL DEFAULT '' AFTER `k175`,
ADD COLUMN `k177` varchar(64) NOT NULL DEFAULT '' AFTER `k176`,
ADD COLUMN `k178` varchar(64) NOT NULL DEFAULT '' AFTER `k177`,
ADD COLUMN `k179` varchar(64) NOT NULL DEFAULT '' AFTER `k178`,
ADD COLUMN `k180` varchar(64) NOT NULL DEFAULT '' AFTER `k179`,

ADD COLUMN `k181` varchar(64) NOT NULL DEFAULT '' AFTER `k180`,
ADD COLUMN `k182` varchar(64) NOT NULL DEFAULT '' AFTER `k181`,
ADD COLUMN `k183` varchar(64) NOT NULL DEFAULT '' AFTER `k182`,
ADD COLUMN `k184` varchar(64) NOT NULL DEFAULT '' AFTER `k183`,
ADD COLUMN `k185` varchar(64) NOT NULL DEFAULT '' AFTER `k184`,
ADD COLUMN `k186` varchar(64) NOT NULL DEFAULT '' AFTER `k185`,
ADD COLUMN `k187` varchar(64) NOT NULL DEFAULT '' AFTER `k186`,
ADD COLUMN `k188` varchar(64) NOT NULL DEFAULT '' AFTER `k187`,
ADD COLUMN `k189` varchar(64) NOT NULL DEFAULT '' AFTER `k188`,
ADD COLUMN `k190` varchar(64) NOT NULL DEFAULT '' AFTER `k189`,

ADD COLUMN `k191` varchar(64) NOT NULL DEFAULT '' AFTER `k190`,
ADD COLUMN `k192` varchar(64) NOT NULL DEFAULT '' AFTER `k191`,
ADD COLUMN `k193` varchar(64) NOT NULL DEFAULT '' AFTER `k192`,
ADD COLUMN `k194` varchar(64) NOT NULL DEFAULT '' AFTER `k193`,
ADD COLUMN `k195` varchar(64) NOT NULL DEFAULT '' AFTER `k194`,
ADD COLUMN `k196` varchar(64) NOT NULL DEFAULT '' AFTER `k195`,
ADD COLUMN `k197` varchar(64) NOT NULL DEFAULT '' AFTER `k196`,
ADD COLUMN `k198` varchar(64) NOT NULL DEFAULT '' AFTER `k197`,
ADD COLUMN `k199` varchar(64) NOT NULL DEFAULT '' AFTER `k198`,
ADD COLUMN `k200` varchar(64) NOT NULL DEFAULT '' AFTER `k199`,

ADD COLUMN `k201` varchar(64) NOT NULL DEFAULT '' AFTER `k200`,
ADD COLUMN `k202` varchar(64) NOT NULL DEFAULT '' AFTER `k201`,
ADD COLUMN `k203` varchar(64) NOT NULL DEFAULT '' AFTER `k202`,
ADD COLUMN `k204` varchar(64) NOT NULL DEFAULT '' AFTER `k203`,
ADD COLUMN `k205` varchar(64) NOT NULL DEFAULT '' AFTER `k204`,
ADD COLUMN `k206` varchar(64) NOT NULL DEFAULT '' AFTER `k205`,
ADD COLUMN `k207` varchar(64) NOT NULL DEFAULT '' AFTER `k206`,
ADD COLUMN `k208` varchar(64) NOT NULL DEFAULT '' AFTER `k207`,
ADD COLUMN `k209` varchar(64) NOT NULL DEFAULT '' AFTER `k208`,
ADD COLUMN `k210` varchar(64) NOT NULL DEFAULT '' AFTER `k209`,

ADD COLUMN `k211` varchar(64) NOT NULL DEFAULT '' AFTER `k210`,
ADD COLUMN `k212` varchar(64) NOT NULL DEFAULT '' AFTER `k211`,
ADD COLUMN `k213` varchar(64) NOT NULL DEFAULT '' AFTER `k212`,
ADD COLUMN `k214` varchar(64) NOT NULL DEFAULT '' AFTER `k213`,
ADD COLUMN `k215` varchar(64) NOT NULL DEFAULT '' AFTER `k214`,
ADD COLUMN `k216` varchar(64) NOT NULL DEFAULT '' AFTER `k215`,
ADD COLUMN `k217` varchar(64) NOT NULL DEFAULT '' AFTER `k216`,
ADD COLUMN `k218` varchar(64) NOT NULL DEFAULT '' AFTER `k217`,
ADD COLUMN `k219` varchar(64) NOT NULL DEFAULT '' AFTER `k218`,
ADD COLUMN `k220` varchar(64) NOT NULL DEFAULT '' AFTER `k219`,

ADD COLUMN `k221` varchar(64) NOT NULL DEFAULT '' AFTER `k220`,
ADD COLUMN `k222` varchar(64) NOT NULL DEFAULT '' AFTER `k221`,
ADD COLUMN `k223` varchar(64) NOT NULL DEFAULT '' AFTER `k222`,
ADD COLUMN `k224` varchar(64) NOT NULL DEFAULT '' AFTER `k223`,
ADD COLUMN `k225` varchar(64) NOT NULL DEFAULT '' AFTER `k224`,
ADD COLUMN `k226` varchar(64) NOT NULL DEFAULT '' AFTER `k225`,
ADD COLUMN `k227` varchar(64) NOT NULL DEFAULT '' AFTER `k226`,
ADD COLUMN `k228` varchar(64) NOT NULL DEFAULT '' AFTER `k227`,
ADD COLUMN `k229` varchar(64) NOT NULL DEFAULT '' AFTER `k228`,
ADD COLUMN `k230` varchar(64) NOT NULL DEFAULT '' AFTER `k229`;


alter table ydy_equipment_result add column `datetimes` varchar(32) not null default '' comment '测试时间' after `record_time`;
alter table ydy_equipment_result add column `report_url` varchar(256) not null default '' comment '报告地址' after `k20`;
#有些业务子系统没有设备管理，那么只能通过设备标志来区分是那个设备上传的数据
alter table ydy_equipment_result add column `equipment_mark` varchar(32) not null default '' comment '设备标志' after `equipment_id`;

insert into ydy_equipment_relation_dict(type,note,is_del,create_time,update_time,create_by) values
(23,'inbody770',0,now(),now(),'兰海军');

INSERT INTO `ydy_equipment_relation` (`type`, `k`, `v`, `note`, `note_en`, `unit`, `is_norm`, `create_by`) VALUES
(23, 'USER_HEIGHT', 'k1', '身高', 'HEIGHT', '', 1, '兰海军'),
(23, 'USER_BIRTHDAY', 'k2', '出生年月', 'BIRTHDAY', '', 0, '兰海军'),
(23, 'USER_GENDER', 'k3', '性别', 'GENDER', '', 1, '兰海军'),
(23, 'USER_AGE', 'k4', '年龄', 'AGE', '', 1, '兰海军'),
(23, 'DATETIMES', 'k5', '测试日期', 'DATETIMES', '', 0, '兰海军'),
(23, 'WT', 'k6', '体重', 'WT', 'kg', 1, '兰海军'),
(23, 'WT_MIN', 'k7', '体重正常范围（下限标准）', 'WT_MIN', '', 0, '兰海军'),
(23, 'WT_MAX', 'k8', '体重正常范围（上限标准）', 'WT_MAX', '', 0, '兰海军'),
(23, 'TBW', 'k9', '身体总水分', 'TBW', 'L', 1, '兰海军'),
(23, 'TBW_MIN', 'k10', '身体总水分（下限标准）', 'TBW_MIN', '', 0, '兰海军'),
(23, 'TBW_MAX', 'k11', '身体总水分（上限标准）', 'TBW_MAX', '', 0, '兰海军'),
(23, 'ICW', 'k12', '细胞内水分', 'ICW', 'L', 1, '兰海军'),
(23, 'ICW_MIN', 'k13', '细胞内水分（下限标准）', 'ICW_MIN', '', 0, '兰海军'),
(23, 'ICW_MAX', 'k14', '细胞内水分（上限标准）', 'ICW_MAX', '', 0, '兰海军'),
(23, 'ECW', 'k15', '细胞外水分', 'ECW', 'L', 1, '兰海军'),
(23, 'ECW_MIN', 'k16', '细胞外水分（下限标准）', 'ECW_MIN', '', 0, '兰海军'),
(23, 'ECW_MAX', 'k17', '细胞外水分（上限标准）', 'ECW_MAX', '', 0, '兰海军'),
(23, 'PROTEIN', 'k18', '蛋白质', 'PROTEIN', 'kg', 1, '兰海军'),
(23, 'PROTEIN_MIN', 'k19', '蛋白质（下限标准）', 'PROTEIN_MIN', '', 0, '兰海军'),
(23, 'PROTEIN_MAX', 'k20', '蛋白质（上限报告）', 'PROTEIN_MAX', '', 0, '兰海军'),
(23, 'MINERAL', 'k21', '无机盐', 'MINERAL', 'kg', 1, '兰海军'),
(23, 'MINERAL_MIN', 'k22', '无机盐（下限标准）', 'MINERAL_MIN', '', 0, '兰海军'),
(23, 'MINERAL_MAX', 'k23', '无机盐（上限标准）', 'MINERAL_MAX', '', 0, '兰海军'),
(23, 'BFM', 'k24', '体脂肪', 'BFM', 'kg', 1, '兰海军'),
(23, 'PBFM_MIN', 'k25', '体脂肪（下限标准）', 'PBFM_MIN', '', 0, '兰海军'),
(23, 'PBFM_MAX', 'k26', '体脂肪（上限标准）', 'PBFM_MAX', '', 0, '兰海军'),
(23, 'SLM', 'k27', '肌肉量', 'SLM', 'kg', 1, '兰海军'),
(23, 'SLM_MIN', 'k28', '肌肉量（下限标准）', 'SLM_MIN', '', 0, '兰海军'),
(23, 'SLM_MAX', 'k29', '肌肉量（上限标准）', 'SLM_MAX', '', 0, '兰海军'),
(23, 'FFM', 'k30', '去脂体重', 'FFM', 'kg', 1, '兰海军'),
(23, 'FFM_MIN', 'k31', '去脂体重（下限标准）', 'FFM_MIN', '', 0, '兰海军'),
(23, 'FFM_MAX', 'k32', '去脂体重（上限标准）', 'FFM_MAX', '', 0, '兰海军'),
(23, 'SMM', 'k33', '骨骼肌', 'SMM', 'kg', 1, '兰海军'),
(23, 'SMM_MIN', 'k34', '骨骼肌（下限标准）', 'SMM_MIN', '', 0, '兰海军'),
(23, 'SMM_MAX', 'k35', '骨骼肌（上限标准）', 'SMM_MAX', '', 0, '兰海军'),
(23, 'BMI', 'k36', '身体质量指数', 'BMI', 'kg/㎡', 1, '兰海军'),
(23, 'BMI_MIN', 'k37', '身体质量指数（下限标准）', 'BMI_MIN', '', 0, '兰海军'),
(23, 'BMI_MAX', 'k38', '身体质量指数（上限标准）', 'BMI_MAX', '', 0, '兰海军'),
(23, 'PBF', 'k39', '体脂百分比', 'PBF', '%', 1, '兰海军'),
(23, 'PBF_MIN', 'k40', '体脂百分比（下限标准)', 'PBF_MIN', '', 0, '兰海军'),
(23, 'PBF_MAX', 'k41', '体脂百分比（上限标准)', 'PBF_MAX', '', 0, '兰海军'),
(23, 'LRA', 'k42', '右上肢肌肉', 'LRA', 'kg', 1, '兰海军'),
(23, 'LRA_MIN', 'k43', '右上肢肌肉（下限标准）', 'LRA_MIN', '', 0, '兰海军'),
(23, 'LRA_MAX', 'k44', '右上肢肌肉（上限标准）', 'LRA_MAX', '', 0, '兰海军'),
(23, 'PILRA', 'k45', '右上肢肌肉比率', 'PILRA', '%', 1, '兰海军'),
(23, 'LLA', 'k46', '左上肢肌肉', 'LLA', 'kg', 1, '兰海军'),
(23, 'LLA_MIN', 'k47', '左上肢肌肉（下限标准）', 'LLA_MIN', '', 0, '兰海军'),
(23, 'LLA_MAX', 'k48', '左上肢肌肉（上限标准）', 'LLA_MAX', '', 0, '兰海军'),
(23, 'PILLA', 'k49', '左上肢肌肉比率', 'PILLA', '%', 1, '兰海军'),
(23, 'LT', 'k50', '躯干肌肉量', 'LT', 'kg', 1, '兰海军'),
(23, 'LT_MIN', 'k51', '躯干肌肉量（下限标准）', 'LT_MIN', '', 0, '兰海军'),
(23, 'LT_MAX', 'k52', '躯干肌肉量（上限标准）', 'LT_MAX', '', 0, '兰海军'),
(23, 'PILT', 'k53', '躯干肌肉量比率', 'PILT', '%', 1, '兰海军'),
(23, 'LRL', 'k54', '右下肢肌肉量', 'LRL', 'kg', 1, '兰海军'),
(23, 'LRL_MIN', 'k55', '右下肢肌肉量（下限标准）', 'LRL_MIN', '', 0, '兰海军'),
(23, 'LRL_MAX', 'k56', '右下肢肌肉量（上限标准）', 'LRL_MAX', '', 0, '兰海军'),
(23, 'PILRL', 'k57', '右下肢肌肉量比率', 'PILRL', '%', 1, '兰海军'),
(23, 'LLL', 'k58', '左下肢肌肉量', 'LLL', 'kg', 1, '兰海军'),
(23, 'LLL_MIN', 'k59', '左下肢肌肉量（下限标准）', 'LLL_MIN', '', 0, '兰海军'),
(23, 'LLL_MAX', 'k60', '左下肢肌肉量（上限标准）', 'LLL_MAX', '', 0, '兰海军'),
(23, 'PILLL', 'k61', '左下肢肌肉量比率', 'PILLL', '%', 1, '兰海军'),
(23, 'WWRA', 'k62', '右上肢总水分', 'WWRA', '', 1, '兰海军'),
(23, 'WWRA_MIN', 'k63', '右上肢总水分（下限标准）', 'WWRA_MIN', '', 0, '兰海军'),
(23, 'WWRA_MAX', 'k64', '右上肢总水分（上限标准）', 'WWRA_MAX', '', 0, '兰海军'),
(23, 'WWLA', 'k65', '左上肢总水分', 'WWLA', '', 1, '兰海军'),
(23, 'WWLA_MIN', 'k66', '左上肢总水分（下限标准）', 'WWLA_MIN', '', 0, '兰海军'),
(23, 'WWLA_MAX', 'k67', '左上肢总水分（上限标准）', 'WWLA_MAX', '', 0, '兰海军'),
(23, 'WWT', 'k68', '躯干水分含量', 'WWT', '', 1, '兰海军'),
(23, 'WWT_MIN', 'k69', '躯干水分含量（下限标准）', 'WWT_MIN', '', 0, '兰海军'),
(23, 'WWT_MAX', 'k70', '躯干水分含量（上限标准）', 'WWT_MAX', '', 0, '兰海军'),
(23, 'WWRL', 'k71', '右下肢总水分', 'WWRL', '', 1, '兰海军'),
(23, 'WWRL_MIN', 'k72', '右下肢总水分（下限标准）', 'WWRL_MIN', '', 0, '兰海军'),
(23, 'WWRL_MAX', 'k73', '右下肢总水分（上限标准）', 'WWRL_MAX', '', 0, '兰海军'),
(23, 'WWLL', 'k74', '左下肢总水分', 'WWLL', '', 1, '兰海军'),
(23, 'WWLL_MIN', 'k75', '左下肢总水分（下限标准）', 'WWLL_MIN', '', 0, '兰海军'),
(23, 'WWLL_MAX', 'k76', '左下肢总水分（上限标准）', 'WWLL_MAX', '', 0, '兰海军'),
(23, 'ICWRA', 'k77', '右上肢细胞内液总量', 'ICWRA', '', 1, '兰海军'),
(23, 'IICWRA_MIN', 'k78', '右上肢细胞内液总量（下限标准）', 'IICWRA_MIN', '', 0, '兰海军'),
(23, 'IICWRA_MAX', 'k79', '右上肢细胞内液总量（上限标准）', 'IICWRA_MAX', '', 0, '兰海军'),
(23, 'ICWLA', 'k80', '左上肢细胞内液总量', 'ICWLA', '', 1, '兰海军'),
(23, 'IICWLA_MIN', 'k81', '左上肢细胞内液总量（下限标准）', 'IICWLA_MIN', '', 0, '兰海军'),
(23, 'IICWLA_MAX', 'k82', '左上肢细胞内液总量（上限标准）', 'IICWLA_MAX', '', 0, '兰海军'),
(23, 'ICWTR', 'k83', '躯干细胞内液总量', 'ICWTR', '', 1, '兰海军'),
(23, 'IICWTR_MIN', 'k84', '躯干细胞内液总量（下限标准）', 'IICWTR_MIN', '', 0, '兰海军'),
(23, 'IICWTR_MAX', 'k85', '躯干细胞内液总量（上限标准）', 'IICWTR_MAX', '', 0, '兰海军'),
(23, 'ICWRL', 'k86', '右下肢细胞内液总量', 'ICWRL', '', 1, '兰海军'),
(23, 'IICWRL_MIN', 'k87', '右下肢细胞内液总量（下限标准）', 'IICWRL_MIN', '', 0, '兰海军'),
(23, 'IICWRL_MAX', 'k88', '右下肢细胞内液总量（上限标准）', 'IICWRL_MAX', '', 0, '兰海军'),
(23, 'ICWLL', 'k89', '左下肢细胞内液总量', 'ICWLL', '', 1, '兰海军'),
(23, 'IICWLL_MIN', 'k90', '左下肢细胞内液总量（下限标准）', 'IICWLL_MIN', '', 0, '兰海军'),
(23, 'IICWLL_MAX', 'k91', '左下肢细胞内液总量（上限标准）', 'IICWLL_MAX', '', 0, '兰海军'),
(23, 'ECWRA', 'k92', '右上肢细胞外液总量', 'ECWRA', '', 1, '兰海军'),
(23, 'IECWRA_MIN', 'k93', '右上肢细胞外液总量（下限标准）', 'IECWRA_MIN', '', 0, '兰海军'),
(23, 'IECWRA_MAX', 'k94', '右上肢细胞外液总量（上限标准）', 'IECWRA_MAX', '', 0, '兰海军'),
(23, 'ECWLA', 'k95', '左上肢细胞外液总量', 'ECWLA', '', 1, '兰海军'),
(23, 'IECWLA_MIN', 'k96', '左上肢细胞外液总量（下限标准）', 'IECWLA_MIN', '', 0, '兰海军'),
(23, 'IECWLA_MAX', 'k97', '左上肢细胞外液总量（上限标准）', 'IECWLA_MAX', '', 0, '兰海军'),
(23, 'ECWTR', 'k98', '躯干细胞外液总量', 'ECWTR', '', 1, '兰海军'),
(23, 'IECWTR_MIN', 'k99', '躯干细胞外液总量（下限标准）', 'IECWTR_MIN', '', 0, '兰海军'),
(23, 'IECWTR_MAX', 'k100', '躯干细胞外液总量（上限标准）', 'IECWTR_MAX', '', 0, '兰海军'),
(23, 'ECWRL', 'k101', '右下肢细胞外液总量', 'ECWRL', '', 1, '兰海军'),
(23, 'IECWRL_MIN', 'k102', '右下肢细胞外液总量（下限标准）', 'IECWRL_MIN', '', 0, '兰海军'),
(23, 'IECWRL_MAX', 'k103', '右下肢细胞外液总量（上限标准）', 'IECWRL_MAX', '', 0, '兰海军'),
(23, 'ECWLL', 'k104', '左下肢细胞外液总量', 'ECWLL', '', 1, '兰海军'),
(23, 'IECWLL_MIN', 'k105', '左下肢细胞外液总量（下限标准）', 'IECWLL_MIN', '', 0, '兰海军'),
(23, 'IECWLL_MAX', 'k106', '左下肢细胞外液总量（上限标准）', 'IECWLL_MAX', '', 0, '兰海军'),
(23, 'WED', 'k107', '细胞外液总量/身体总水分', 'WED', '', 1, '兰海军'),
(23, 'WEDRA', 'k108', '右上肢细胞外液总量/身体总水分', 'WEDRA', '', 1, '兰海军'),
(23, 'WEDLA', 'k109', '左上肢细胞外液总量/身体总水分', 'WEDLA', '', 1, '兰海军'),
(23, 'WEDT', 'k110', '躯干细胞外液总量/身体总水分', 'WEDT', '', 1, '兰海军'),
(23, 'WEDRL', 'k111', '右下肢细胞外液总量/身体总水分', 'WEDRL', '', 1, '兰海军'),
(23, 'WEDLL', 'k112', '左下肢细胞外液总量/身体总水分', 'WEDLL', '', 1, '兰海军'),
(23, 'FRA', 'k113', '右上肢脂肪含量', 'FRA', 'kg', 1, '兰海军'),
(23, 'PFRA', 'k114', '右上肢脂肪百分比', 'PFRA', '%', 1, '兰海军'),
(23, 'FLA', 'k115', '左上肢脂肪含量', 'FLA', 'kg', 1, '兰海军'),
(23, 'PFLA', 'k116', '左上肢脂肪百分比', 'PFLA', '%', 1, '兰海军'),
(23, 'FT', 'k117', '躯干脂肪含量', 'FT', 'kg', 1, '兰海军'),
(23, 'PFT', 'k118', '躯干脂肪百分比', 'PFT', '%', 1, '兰海军'),
(23, 'FRL', 'k119', '右下肢脂肪含量', 'FRL', 'kg', 1, '兰海军'),
(23, 'PFRL', 'k120', '右下肢脂肪百分比', 'PFRL', '%', 1, '兰海军'),
(23, 'FLL', 'k121', '左下肢脂肪含量', 'FLL', 'kg', 1, '兰海军'),
(23, 'PFLL', 'k122', '左下肢脂肪百分比', 'PFLL', '%', 1, '兰海军'),
(23, 'FS', 'k123', '健康评估分数', 'FS', '分', 1, '兰海军'),
(23, 'TW', 'k124', '目标体重', 'TW', 'kg', 1, '兰海军'),
(23, 'WC', 'k125', '体重控制', 'WC', 'kg', 1, '兰海军'),
(23, 'FC', 'k126', '脂肪控制', 'FC', 'kg', 1, '兰海军'),
(23, 'MC', 'k127', '肌肉控制', 'MC', 'kg', 1, '兰海军'),
(23, 'BMR', 'k128', '基础代谢', 'BMR', 'kcal', 1, '兰海军'),
(23, 'WHR', 'k129', '腰臀比', 'WHR', '', 1, '兰海军'),
(23, 'WHR_MIN', 'k130', '腰臀比（下限标准）', 'WHR_MIN', '', 0, '兰海军'),
(23, 'WHR_MAX', 'k131', '腰臀比（上限标准）', 'WHR_MAX', '', 0, '兰海军'),
(23, 'VFL', 'k132', '内脏脂肪等级', 'VFL', '', 1, '兰海军'),
(23, 'VFA', 'k133', '内脏脂肪面积', 'VFA', 'c㎡', 1, '兰海军'),
(23, 'OBESITY', 'k134', '肥胖度', 'OBESITY', '', 1, '兰海军'),
(23, 'OD_MIN', 'k135', '肥胖度（下限标准）', 'OD_MIN', '', 0, '兰海军'),
(23, 'OD_MAX', 'k136', '肥胖度（上限标准）', 'OD_MAX', '', 0, '兰海军'),
(23, 'BCM', 'k137', '身体细胞量', 'BCM', '', 1, '兰海军'),
(23, 'BCM_MIN', 'k138', '身体细胞量（上限标准）', 'BCM_MIN', '', 0, '兰海军'),
(23, 'BCM_MAX', 'k139', '身体细胞量（下限标准）', 'BCM_MAX', '', 0, '兰海军'),
(23, 'AC', 'k140', '上臂围度', 'AC', '', 1, '兰海军'),
(23, 'AMC', 'k141', '上臂肌肉围度', 'AMC', '', 1, '兰海军'),
(23, 'BMC', 'k142', '骨矿物质含量', 'BMC', 'kg', 1, '兰海军'),
(23, 'BMC_MIN', 'k143', '骨矿物质含量（下限标准）', 'BMC_MIN', '', 0, '兰海军'),
(23, 'BMC_MAX', 'k144', '骨矿物质含量（上限标准）', 'BMC_MAX', '', 0, '兰海军'),
(23, 'TBWFFM', 'k145', '身体总水分/去脂体重', 'TBWFFM', '', 1, '兰海军'),
(23, 'FFMI', 'k146', '去脂体重指数', 'FFMI', '', 1, '兰海军'),
(23, 'BFMI', 'k147', '体脂肪指数', 'BFMI', '', 1, '兰海军'),
(23, 'IRA1', 'k148', '1kHz-右上肢阻抗', 'IRA1', '', 1, '兰海军'),
(23, 'ILA1', 'k149', '1kHz-左上肢阻抗', 'ILA1', '', 1, '兰海军'),
(23, 'IT1', 'k150', '1kHz-躯干阻抗', 'IT1', '', 1, '兰海军'),
(23, 'IRL1', 'k151', '1kHz-右下肢阻抗', 'IRL1', '', 1, '兰海军'),
(23, 'ILL1', 'k152', '1kHz-左下肢阻抗', 'ILL1', '', 1, '兰海军'),
(23, 'IRA5', 'k153', '5kHz-右上肢阻抗', 'IRA5', '', 1, '兰海军'),
(23, 'ILA5', 'k154', '5kHz-左上肢阻抗', 'ILA5', '', 1, '兰海军'),
(23, 'IT5', 'k155', '5kHz-躯干阻抗', 'IT5', '', 1, '兰海军'),
(23, 'IRL5', 'k156', '5kHz-右下肢阻抗', 'IRL5', '', 1, '兰海军'),
(23, 'ILL5', 'k157', '5kHz-左下肢阻抗', 'ILL5', '', 1, '兰海军'),
(23, 'IRA50', 'k158', '50kHz-右上肢阻抗', 'IRA50', '', 1, '兰海军'),
(23, 'ILA50', 'k159', '50kHz-左上肢阻抗', 'ILA50', '', 1, '兰海军'),
(23, 'IT50', 'k160', '50kHz-躯干阻抗', 'IT50', '', 1, '兰海军'),
(23, 'IRL50', 'k161', '50kHz-右下肢阻抗', 'IRL50', '', 1, '兰海军'),
(23, 'ILL50', 'k162', '50kHz-左下肢阻抗', 'ILL50', '', 1, '兰海军'),
(23, 'IRA250', 'k163', '250kHz-右上肢阻抗', 'IRA250', '', 1, '兰海军'),
(23, 'ILA250', 'k164', '250kHz-左上肢阻抗', 'ILA250', '', 1, '兰海军'),
(23, 'IT250', 'k165', '250kHz-躯干阻抗', 'IT250', '', 1, '兰海军'),
(23, 'IRL250', 'k166', '250kHz-右下肢阻抗', 'IRL250', '', 1, '兰海军'),
(23, 'ILL250', 'k167', '250kHz-左下肢阻抗', 'ILL250', '', 1, '兰海军'),
(23, 'IRA500', 'k168', '500kHz-右上肢阻抗', 'IRA500', '', 1, '兰海军'),
(23, 'ILA500', 'k169', '500kHz-左上肢阻抗', 'ILA500', '', 1, '兰海军'),
(23, 'IT500', 'k170', '500kHz-躯干阻抗', 'IT500', '', 1, '兰海军'),
(23, 'IRL500', 'k171', '500kHz-右下肢阻抗', 'IRL500', '', 1, '兰海军'),
(23, 'ILL500', 'k172', '500kHz-左下肢阻抗', 'ILL500', '', 1, '兰海军'),
(23, 'IRA1M', 'k173', '1000kHz-右上肢阻抗', 'IRA1M', '', 1, '兰海军'),
(23, 'ILA1M', 'k174', '1000kHz-左上肢阻抗', 'ILA1M', '', 1, '兰海军'),
(23, 'IT1M', 'k175', '1000kHz-躯干阻抗', 'IT1M', '', 1, '兰海军'),
(23, 'IRL1M', 'k176', '1000kHz-右下肢阻抗', 'IRL1M', '', 1, '兰海军'),
(23, 'ILL1M', 'k177', '1000kHz-左下肢阻抗', 'ILL1M', '', 1, '兰海军'),
(23, 'xra5', 'k178', '5kHz-右上肢电抗', 'xra5', '', 1, '兰海军'),
(23, 'xla5', 'k179', '5kHz-左上肢电抗', 'xla5', '', 1, '兰海军'),
(23, 'xtr5', 'k180', '5kHz-躯干电抗', 'xtr5', '', 1, '兰海军'),
(23, 'xrl5', 'k181', '5kHz-右下肢电抗', 'xrl5', '', 1, '兰海军'),
(23, 'xll5', 'k182', '5kHz-左下肢电抗', 'xll5', '', 1, '兰海军'),
(23, 'xra50', 'k183', '50kHz-右上肢电抗', 'xra50', '', 1, '兰海军'),
(23, 'xla50', 'k184', '50kHz-左上肢电抗', 'xla50', '', 1, '兰海军'),
(23, 'xtr50', 'k185', '50kHz-躯干电抗', 'xtr50', '', 1, '兰海军'),
(23, 'xrl50', 'k186', '50kHz-右下肢电抗', 'xrl50', '', 1, '兰海军'),
(23, 'xll50', 'k187', '50kHz-左下肢电抗', 'xll50', '', 1, '兰海军'),
(23, 'xra250', 'k188', '250kHz-右上肢电抗', 'xra250', '', 1, '兰海军'),
(23, 'xla250', 'k189', '250kHz-左上肢电抗', 'xla250', '', 1, '兰海军'),
(23, 'xtr250', 'k190', '250kHz-躯干电抗', 'xtr250', '', 1, '兰海军'),
(23, 'xrl250', 'k191', '250kHz-右下肢电抗', 'xrl250', '', 1, '兰海军'),
(23, 'xll250', 'k192', '250kHz-左下肢电抗', 'xll250', '', 1, '兰海军'),
(23, 'ALGLERA50', 'k193', '50kHz右上肢相位角', 'ALGLERA50', '', 1, '兰海军'),
(23, 'ALGLELA50', 'k194', '50kHz左上肢相位角', 'ALGLELA50', '', 1, '兰海军'),
(23, 'ALGLET50', 'k195', '50kHz躯干相位角', 'ALGLET50', '', 1, '兰海军'),
(23, 'ALGLERL50', 'k196', '50kHz右下肢相位角', 'ALGLERL50', '', 1, '兰海军'),
(23, 'ALGLELL50', 'k197', '50kHz左下肢相位角', 'ALGLELL50', '', 1, '兰海军'),
(23, 'WBPA50', 'k198', '50kHz总相位角', 'WBPA50', '', 1, '兰海军'),
(23, 'NECK', 'k199', '颈部围度', 'NECK', '', 1, '兰海军'),
(23, 'CHEST', 'k200', '胸围', 'CHEST', '', 1, '兰海军'),
(23, 'ABD', 'k201', '腰围', 'ABD', '', 1, '兰海军'),
(23, 'HIP', 'k202', '臀围', 'HIP', '', 1, '兰海军'),
(23, 'ACR', 'k203', '右上臂围度', 'ACR', '', 1, '兰海军'),
(23, 'ACL', 'k204', '左上臂围度', 'ACL', '', 1, '兰海军'),
(23, 'THIGHR', 'k205', '右下肢围度', 'THIGHR', '', 1, '兰海军'),
(23, 'THIGHL', 'k206', '左下肢围度', 'THIGHL', '', 1, '兰海军'),
(23, 'TOT_SCORE', 'k207', '儿童成长指数', 'TOT_SCORE', '', 1, '兰海军'),
(23, 'ODK', 'k208', '儿童肥胖程度', 'ODK', '', 1, '兰海军'),
(23, 'ODK_MIN', 'k209', '儿童肥胖程度（下限标准）', 'ODK_MIN', '', 0, '兰海军'),
(23, 'ODK_MAX', 'k210', '儿童肥胖程度（上限标准）', 'ODK_MAX', '', 0, '兰海军'),
(23, 'SPHYG1', 'k211', '收缩压', 'SPHYG1', '', 1, '兰海军'),
(23, 'SPHYG2', 'k212', '舒张压', 'SPHYG2', '', 1, '兰海军'),
(23, 'SPHYG3', 'k213', '脉搏', 'SPHYG3', '', 1, '兰海军'),
(23, 'MeanArteryPressure', 'k214', '平均动脉压', 'MeanArteryPressure', '', 1, '兰海军'),
(23, 'PulsePressure', 'k215', '脉压', 'PulsePressure', '', 1, '兰海军'),
(23, 'RatePressureProduct', 'k216', '心率-收缩压乘积', 'RatePressureProduct', '', 1, '兰海军'),
(23, 'EQUIP', 'k217', 'InBody型号', 'EQUIP', '', 0, '兰海军'),
(23, 'BSMI', 'k218', 'SMI', 'BSMI', '', 1, '兰海军'),
(23, 'SICK_SN', 'k219', '病历', 'SICK_SN', '', 0, '兰海军'),
(23, 'GROUP_SN', 'k220', '组', 'GROUP_SN', '', 0, '兰海军'),
(23, 'RENERGY', 'k221', '建议摄入热量', 'RENERGY', '', 1, '兰海军'),
(23, 'BMR_MIN', 'k222', '基础代谢率（下限标准）', 'BMR_MIN', '', 0, '兰海军'),
(23, 'BMR_MAX', 'k223', '基础代谢率（上限标准）', 'BMR_MAX', '', 0, '兰海军'),
(23, 'SMIW_B', 'k224', '', 'SMIW_B', '', 1, '兰海军'),
(23, 'ORDER_DATE', 'k225', '注册日期', 'ORDER_DATE', '', 0, '兰海军');

#指标含义（英文）
alter table ydy_equipment_relation add column  `note_en` varchar(128) NOT NULL DEFAULT '' COMMENT '英文备注' after `note`;

-- k5心肺指标 2024-03-04 wiscourper
insert into ydy_equipment_relation_dict(type,note,is_del,create_time,update_time,create_by) values
(24,'cosmedK5',0,now(),now(),'兰海军');

insert into ydy_equipment_relation_dict(type,note,is_del,create_time,update_time,create_by) values
(25,'cosmedK5process',0,now(),now(),'兰海军');

--k5设备映射关系表
INSERT INTO `ydy_equipment_relation` (`type`, `k`, `v`, `note`, `note_en`, `unit`, `is_norm`, `create_by`) VALUES
(24, 'height', 'k1', '身高', 'height', 'cm', 1, '兰海军'),
(24, 'age', 'k2', '年龄', 'age', 'y', 1, '兰海军'),
(24, 'body_weight', 'k3', '体重', 'body_weight', 'kg', 1, '兰海军'),
(24, 'gender', 'k4', '性别', 'gender', '', 1, '兰海军'),
(24, 'VO2', 'k5', '', 'VO2', 'mL/min', 1, '兰海军'),
(24, 'VO2/Kg', 'k6', '', 'VO2/Kg', 'mL/min/Kg', 1, '兰海军'),
(24, 'METS', 'k7', '', 'METS', '', 1, '兰海军'),
(24, 'RQ', 'k8', 'RER/max', 'RQ', '', 1, '兰海军'),
(24, 'VE', 'k9', '', 'VE', 'L/min', 1, '兰海军'),
(24, 'BR', 'k10', '', 'BR', '%', 1, '兰海军'),
(24, 'VT', 'k11', '', 'VT', 'L(btps)', 1, '兰海军'),
(24, 'RF', 'k12', '', 'RF', '1/min', 1, '兰海军'),
(24, 'HR', 'k13', '', 'HR', 'bpm', 1, '兰海军'),
(24, 'HRR', 'k14', '', 'HRR', 'bpm', 1, '兰海军'),
(24, 'VO2/HR', 'k15', '', 'VO2/HR', 'mL/beat', 1, '兰海军'),
(24, 'PetCO2', 'k16', '', 'PetCO2', 'mmHg', 1, '兰海军'),
(24, 'PetO2', 'k17', '', 'PetO2', 'mmHg', 1, '兰海军'),
(24, 'VE/VO2', 'k18', '', 'VE/VO2', '', 1, '兰海军'),
(24, 'VE/VCO2', 'k19', '', 'VE/VCO2', '', 1, '兰海军'),
(24, 't', 'k20', '时间', 't', 's', 1, '兰海军'),
(24, 'Speed', 'k21', '', 'Speed', 'Kmh', 1, '兰海军'),
(24, 'Grade', 'k22', '', 'Grade', '%', 1, '兰海军'),
(24, 'Power', 'k23', '', 'Power', 'Watt', 1, '兰海军'),
(24, 'LAC', 'k24', '', '', 'mmol/L', 0, '兰海军');


INSERT INTO `ydy_equipment_relation` (`type`, `k`, `v`, `note`, `note_en`, `unit`, `is_norm`, `create_by`) VALUES
(25, 't', 'k1', '', 't', 's', 0, '兰海军'),
(25, 'RF', 'k2', '', 'RF', '1/min', 0, '兰海军'),
(25, 'VT', 'k3', '', 'VT', 'L(btps)', 0, '兰海军'),
(25, 'VE', 'k4', '', 'VE', 'L/min', 0, '兰海军'),
(25, 'IV', 'k5', '', 'IV', 'mL', 0, '兰海军'),
(25, 'VO2', 'k6', '', 'VO2', 'mL/min', 0, '兰海军'),
(25, 'VCO2', 'k7', '', 'VCO2', 'mL/min', 0, '兰海军'),
(25, 'RQ', 'k8', '', 'RQ', '---', 0, '兰海军'),
(25, 'O2exp', 'k9', '', 'O2exp', 'mL', 0, '兰海军'),
(25, 'CO2exp', 'k10', '', 'CO2exp', 'mL', 0, '兰海军'),
(25, 'VE/VO2', 'k11', '', 'VE/VO2', '---', 0, '兰海军'),
(25, 'VE/VCO2', 'k12', '', 'VE/VCO2', '---', 0, '兰海军'),
(25, 'VO2/Kg', 'k13', '', 'VO2/Kg', 'mL/min/Kg', 0, '兰海军'),
(25, 'METS', 'k14', '', 'METS', '---', 0, '兰海军'),
(25, 'HR', 'k15', '', 'HR', 'bpm', 0, '兰海军'),
(25, 'VO2/HR', 'k16', '', 'VO2/HR', 'mL/beat', 0, '兰海军'),
(25, 'FeO2', 'k17', '', 'FeO2', '%', 0, '兰海军'),
(25, 'FeCO2', 'k18', '', 'FeCO2', '%', 0, '兰海军'),
(25, 'FetO2', 'k19', '', 'FetO2', '%', 0, '兰海军'),
(25, 'FetCO2', 'k20', '', 'FetCO2', '%', 0, '兰海军'),
(25, 'FiO2', 'k21', '', 'FiO2', '%', 0, '兰海军'),
(25, 'FiCO2', 'k22', '', 'FiCO2', '%', 0, '兰海军'),
(25, 'PeO2', 'k23', '', 'PeO2', 'mmHg', 0, '兰海军'),
(25, 'PeCO2', 'k24', '', 'PeCO2', 'mmHg', 0, '兰海军'),
(25, 'PetO2', 'k25', '', 'PetO2', 'mmHg', 0, '兰海军'),
(25, 'PetCO2', 'k26', '', 'PetCO2', 'mmHg', 0, '兰海军'),
(25, 'Power', 'k27', '', 'Power', 'Watt', 0, '兰海军'),
(25, '阶段', 'k28', '', '阶段', '---', 0, '兰海军'),
(25, '标记', 'k29', '', '标记', '---', 0, '兰海军'),
(25, '湿度，温度', 'k30', '', '湿度，温度', '°C', 0, '兰海军'),
(25, 'RH Amb', 'k31', '', 'RH Amb', '%', 0, '兰海军'),
(25, '设备温度', 'k32', '', '设备温度', '°C', 0, '兰海军'),
(25, '分析压力', 'k33', '', '分析压力', 'mmHg', 0, '兰海军'),
(25, 'PB', 'k34', '', 'PB', 'mmHg', 0, '兰海军'),
(25, 'EEkc', 'k35', '', 'EEkc', 'kcal/day', 0, '兰海军'),
(25, 'EEh', 'k36', '', 'EEh', 'kcal/h', 0, '兰海军'),
(25, 'EEm', 'k37', '', 'EEm', 'kcal/min', 0, '兰海军'),
(25, 'EEtot', 'k38', '', 'EEtot', 'kcal', 0, '兰海军'),
(25, 'EEkg', 'k39', '', 'EEkg', 'kcal/Kg/day', 0, '兰海军'),
(25, 'PRO', 'k40', '', 'PRO', 'kcal/day', 0, '兰海军'),
(25, 'FAT', 'k41', '', 'FAT', 'kcal/day', 0, '兰海军'),
(25, 'CHO', 'k42', '', 'CHO', 'kcal/day', 0, '兰海军'),
(25, 'PRO%', 'k43', '', 'PRO%', '%', 0, '兰海军'),
(25, 'FAT%', 'k44', '', 'FAT%', '%', 0, '兰海军'),
(25, 'CHO%', 'k45', '', 'CHO%', '%', 0, '兰海军'),
(25, 'npRQ', 'k46', '', 'npRQ', '---', 0, '兰海军'),
(25, 'Long', 'k47', '', 'Long', '° '' "', 0, '兰海军'),
(25, 'Lat', 'k48', '', 'Lat', '° '' "', 0, '兰海军'),
(25, 'GPS高度', 'k49', '', 'GPS高度', 'm', 0, '兰海军'),
(25, 'Barom_Altitude', 'k50', '', 'Barom_Altitude', 'm', 0, '兰海军'),
(25, 'GPS Speed', 'k51', '', 'GPS Speed', 'km/h', 0, '兰海军'),
(25, 'GPS距离', 'k52', '', 'GPS距离', 'm', 0, '兰海军'),
(25, 'Ti', 'k53', '', 'Ti', 's', 0, '兰海军'),
(25, 'Te', 'k54', '', 'Te', 's', 0, '兰海军'),
(25, 'Ttot', 'k55', '', 'Ttot', 's', 0, '兰海军'),
(25, 'Ti/Ttot', 'k56', '', 'Ti/Ttot', '---', 0, '兰海军'),
(25, 'VD/VT e', 'k57', '', 'VD/VT e', '---', 0, '兰海军'),
(25, 'LogVE', 'k58', '', 'LogVE', 'L/min', 0, '兰海军'),
(25, 't Rel', 'k59', '', 't Rel', 's', 0, '兰海军'),
(25, '标记速度', 'k60', '', '标记速度', 'm/s', 0, '兰海军'),
(25, 'mark Dist.', 'k61', '', 'mark Dist.', 'm', 0, '兰海军'),
(25, '电池', 'k62', '', '电池', '%', 0, '兰海军'),
(25, '阶段时间', 'k63', '', '阶段时间', 'hh:mm:ss', 0, '兰海军'),
(25, 'VO2%Pred', 'k64', '', 'VO2%Pred', '%', 0, '兰海军'),
(25, 'VO2/Kg%Pred', 'k65', '', 'VO2/Kg%Pred', '%', 0, '兰海军'),
(25, 'BR', 'k66', '', 'BR', '%', 0, '兰海军'),
(25, 'O2延迟', 'k67', '', 'O2延迟', 'ms', 0, '兰海军'),
(25, 'CO2 Delay', 'k68', '', 'CO2 Delay', 'ms', 0, '兰海军'),
(25, 'GPS定向', 'k69', '', 'GPS定向', 'DEG', 0, '兰海军'),
(25, 'RH Sample', 'k70', '', 'RH Sample', '%', 0, '兰海军'),
(25, '步伐节奏', 'k71', '', '步伐节奏', '1/min', 0, '兰海军'),
(25, '卫星', 'k72', '', '卫星', '---', 0, '兰海军'),
(25, '定位', 'k73', '', '定位', '---', 0, '兰海军'),
(25, 'Satellites SNR', 'k74', '', 'Satellites SNR', 'dB', 0, '兰海军'),
(25, 'VT/Ti', 'k75', '', 'VT/Ti', '---', 0, '兰海军'),
(25, 'HRR', 'k76', '', 'HRR', 'bpm', 0, '兰海军'),
(25, 'PaCO2_e', 'k77', '', 'PaCO2_e', 'mmHg', 0, '兰海军'),
(25, 'SV', 'k78', '', 'SV', 'mL', 0, '兰海军'),
(25, 'CO', 'k79', '', 'CO', 'L/min', 0, '兰海军');

ALTER TABLE `ydy_equipment_process_extend`
ADD COLUMN `k31` varchar(64) NOT NULL DEFAULT '' AFTER `k30`,
ADD COLUMN `k32` varchar(64) NOT NULL DEFAULT '' AFTER `k31`,
ADD COLUMN `k33` varchar(64) NOT NULL DEFAULT '' AFTER `k32`,
ADD COLUMN `k34` varchar(64) NOT NULL DEFAULT '' AFTER `k33`,
ADD COLUMN `k35` varchar(64) NOT NULL DEFAULT '' AFTER `k34`,
ADD COLUMN `k36` varchar(64) NOT NULL DEFAULT '' AFTER `k35`,
ADD COLUMN `k37` varchar(64) NOT NULL DEFAULT '' AFTER `k36`,
ADD COLUMN `k38` varchar(64) NOT NULL DEFAULT '' AFTER `k37`,
ADD COLUMN `k39` varchar(64) NOT NULL DEFAULT '' AFTER `k38`,
ADD COLUMN `k40` varchar(64) NOT NULL DEFAULT '' AFTER `k39`,

ADD COLUMN `k41` varchar(64) NOT NULL DEFAULT '' AFTER `k40`,
ADD COLUMN `k42` varchar(64) NOT NULL DEFAULT '' AFTER `k41`,
ADD COLUMN `k43` varchar(64) NOT NULL DEFAULT '' AFTER `k42`,
ADD COLUMN `k44` varchar(64) NOT NULL DEFAULT '' AFTER `k43`,
ADD COLUMN `k45` varchar(64) NOT NULL DEFAULT '' AFTER `k44`,
ADD COLUMN `k46` varchar(64) NOT NULL DEFAULT '' AFTER `k45`,
ADD COLUMN `k47` varchar(64) NOT NULL DEFAULT '' AFTER `k46`,
ADD COLUMN `k48` varchar(64) NOT NULL DEFAULT '' AFTER `k47`,
ADD COLUMN `k49` varchar(64) NOT NULL DEFAULT '' AFTER `k48`,
ADD COLUMN `k50` varchar(64) NOT NULL DEFAULT '' AFTER `k49`,

ADD COLUMN `k51` varchar(64) NOT NULL DEFAULT '' AFTER `k50`,
ADD COLUMN `k52` varchar(64) NOT NULL DEFAULT '' AFTER `k51`,
ADD COLUMN `k53` varchar(64) NOT NULL DEFAULT '' AFTER `k52`,
ADD COLUMN `k54` varchar(64) NOT NULL DEFAULT '' AFTER `k53`,
ADD COLUMN `k55` varchar(64) NOT NULL DEFAULT '' AFTER `k54`,
ADD COLUMN `k56` varchar(64) NOT NULL DEFAULT '' AFTER `k55`,
ADD COLUMN `k57` varchar(64) NOT NULL DEFAULT '' AFTER `k56`,
ADD COLUMN `k58` varchar(64) NOT NULL DEFAULT '' AFTER `k57`,
ADD COLUMN `k59` varchar(64) NOT NULL DEFAULT '' AFTER `k58`,
ADD COLUMN `k60` varchar(64) NOT NULL DEFAULT '' AFTER `k59`,

ADD COLUMN `k61` varchar(64) NOT NULL DEFAULT '' AFTER `k60`,
ADD COLUMN `k62` varchar(64) NOT NULL DEFAULT '' AFTER `k61`,
ADD COLUMN `k63` varchar(64) NOT NULL DEFAULT '' AFTER `k62`,
ADD COLUMN `k64` varchar(64) NOT NULL DEFAULT '' AFTER `k63`,
ADD COLUMN `k65` varchar(64) NOT NULL DEFAULT '' AFTER `k64`,
ADD COLUMN `k66` varchar(64) NOT NULL DEFAULT '' AFTER `k65`,
ADD COLUMN `k67` varchar(64) NOT NULL DEFAULT '' AFTER `k66`,
ADD COLUMN `k68` varchar(64) NOT NULL DEFAULT '' AFTER `k67`,
ADD COLUMN `k69` varchar(64) NOT NULL DEFAULT '' AFTER `k68`,
ADD COLUMN `k70` varchar(64) NOT NULL DEFAULT '' AFTER `k69`,

ADD COLUMN `k71` varchar(64) NOT NULL DEFAULT '' AFTER `k70`,
ADD COLUMN `k72` varchar(64) NOT NULL DEFAULT '' AFTER `k71`,
ADD COLUMN `k73` varchar(64) NOT NULL DEFAULT '' AFTER `k72`,
ADD COLUMN `k74` varchar(64) NOT NULL DEFAULT '' AFTER `k73`,
ADD COLUMN `k75` varchar(64) NOT NULL DEFAULT '' AFTER `k74`,
ADD COLUMN `k76` varchar(64) NOT NULL DEFAULT '' AFTER `k75`,
ADD COLUMN `k77` varchar(64) NOT NULL DEFAULT '' AFTER `k76`,
ADD COLUMN `k78` varchar(64) NOT NULL DEFAULT '' AFTER `k77`,
ADD COLUMN `k79` varchar(64) NOT NULL DEFAULT '' AFTER `k78`,
ADD COLUMN `k80` varchar(64) NOT NULL DEFAULT '' AFTER `k79`;

ALTER TABLE `ydy_equipment_process_extend`
ADD COLUMN `other_info` text comment '其他信息' AFTER `k80`;

alter table ydy_equipment_result add column `filename` varchar(256) not null DEFAULT '' COMMENT '原始数据文件' after `reference`;
alter table ydy_equipment_result add column `filemtime` varchar(24) not null DEFAULT '' COMMENT '原始数据文件修改时间' after `filename`;

-- 易力加T232指标 2024-03-04 wiscourper
insert into ydy_equipment_relation_dict(type,note,is_del,create_time,update_time,create_by) values
(26,'eligaT232',0,now(),now(),'兰海军');
-- 易力加T232过程指标
insert into ydy_equipment_relation_dict(type,note,is_del,create_time,update_time,create_by) values
(27,'eligaT232process',0,now(),now(),'兰海军');

-- 结果指标
insert into ydy_equipment_relation(type,k,v,note,note_en,unit,is_norm,create_by)
values 
('26','MaxPeakPower','k1','最大峰值功率','Max Peak Power','w','1','兰海军'),
('26','MaxAvgPower','k2','最大平均功率','Max Avg Power','w','1','兰海军'),
('26','MaxPeakSpeed','k3','最大峰值速度','Max Peak Speed','m/s','1','兰海军'),
('26','MaxAvgSpeed','k4','最大平均速度','Max Avg Speed','m/s','1','兰海军'),
('26','MaxPeakRfd','k5','最大峰值Rfd','Max Peak Rfd','','1','兰海军'),
('26','MaxAvgRfd','k6','最大平均Rfd','Max Avg Rfd','','1','兰海军'),

('26','TotalConPower','k7','总向心功率','Total Concentric Power','w','1','兰海军'),
('26','TotalEccPower','k8','总离心功率','Total Eccentric Power','w','1','兰海军'),
('26','ConPeakPower','k9','向心峰值功率','Concentric Peak Power','w','1','兰海军'),
('26','EccPeakPower','k10','离心峰值功率','Eccentric Peak Power','w','1','兰海军'),
('26','Times','k11','次数','Times','','1','兰海军'),

('26','PeakPowerAvg','k12','峰值功率均值','Peak Power Avg','w','0','兰海军'),
('26','AvgPowerAvg','k13','平均功率均值','Avg Power Avg','w','0','兰海军'),
('26','PeakSpeedAvg','k14','峰值速度均值','Peak Speed Avg','m/s','0','兰海军'),
('26','AvgSpeedAvg','k15','平均速度均值','Avg Speed Avg','m/s','0','兰海军'),
('26','PeakRfdAvg','k16','峰值Rfd均值','Peak Rfd Avg','','0','兰海军'),
('26','AvgRfdAvg','k17','平均Rfd均值','Avg Rfd Avg','','0','兰海军'),

('26','trainStime','k18','开始时间','','','0','兰海军'),
('26','trainEtime','k19','结束时间','','','0','兰海军'),
('26','modeId','k20','模式id','','','0','兰海军'),
('26','modeName','k21','模式名称','','','0','兰海军'),
('26','actionName','k22','动作名称','','','0','兰海军'),
('26','modelId','k23','型号id','','','0','兰海军'),
('26','modelName','k24','型号名称','','','0','兰海军'),
('26','modelDesc','k25','型号描述','','','0','兰海军'),
('26','deviceType','k26','设备类型','','','0','兰海军');

-- 过程指标
insert into ydy_equipment_relation(type,k,v,note,note_en,unit,is_norm,create_by)
values 
('type','k','v','note','note_en','unit','is_norm','create_by'),
('27','avgPower','k1','平均功率','','w','1','兰海军'),
('27','avgRfd','k2','平均Rfd','','','1','兰海军'),
('27','avgSpeed','k3','平均速度','','m/s','1','兰海军'),
('27','maxPower','k4','峰值功率','','w','1','兰海军'),
('27','maxRfd','k5','峰值Rfd','','','1','兰海军'),
('27','maxSpeed','k6','峰值速度','','m/s','1','兰海军'),
('27','maxLoad','k7','最大负荷','','kg','0','兰海军'),
('27','targetLoad','k8','目标负荷','','kg','0','兰海军'),
('27','targetPower','k9','目标功率','','w','0','兰海军'),
('27','targetRfd','k10','目标Rfd','','','0','兰海军'),
('27','ecc','k11','1向心2离心','','','0','兰海军'),
('27','energy','k12','能量','','','0','兰海军'),
('27','indexId','k13','index的id两个一对','','','0','兰海军'),
('27','indexGroup','k14','','','','0','兰海军'),
('27','direction','k15','','','','0','兰海军');

-- 2023-03-14 Vald测力板 wiscourper
-- Vald结果数据
insert into ydy_equipment_relation_dict(type,note,is_del,create_time,update_time,create_by) values
(28,'Vald',0,now(),now(),'兰海军');
-- Vald过程数据
insert into ydy_equipment_relation_dict(type,note,is_del,create_time,update_time,create_by) values
(29,'Valdprocess',0,now(),now(),'兰海军');

-- humac等速肌力结果数据
insert into ydy_equipment_relation_dict(type,note,is_del,create_time,update_time,create_by) values
(30,'humac等速肌力',0,now(),now(),'兰海军');
-- humac等速肌力过程数据
insert into ydy_equipment_relation_dict(type,note,is_del,create_time,update_time,create_by) values
(31,'humac等速肌力process',0,now(),now(),'兰海军');

insert into ydy_equipment_relation(type,k,v,note,note_en,unit,is_norm,create_by)
values 
('30','FullName','k1','全称','FullName','','0','lhj'),
('30','ID','k2','ID','ID','','0','lhj'),
('30','BirthDate','k3','生日','BirthDate','','1','lhj'),
('30','Age','k4','年龄','Age','','1','lhj'),
('30','Sex','k5','性别','Sex','','1','lhj'),
('30','Height','k6','身高','Height','','1','lhj'),
('30','Machine','k7','设备','Machine','','0','lhj'),
('30','Test','k8','是否测试','Test','','1','lhj'),
('30','PeakTorque','k9','PeakTorque','Peak Torque (Foot-Pounds - Best Repetition)','','1','lhj'),
('30','WorkPerRepetition','k10','','Work per Repetition (Foot-Pounds - Best Repetition)','','1','lhj'),
('30','AveragePowerPerRepetition','k11','','Average Power per Repetition (Watts - Best Repetition)','','1','lhj'),
('30','JointAngleAtPeakTorque','k12','','Joint Angle at Peak Torque (Degrees)','','1','lhj'),
('30','RangeOfMotion','k13','','Range of Motion (Degrees)','','1','lhj'),
('30','TimeToPeakTorque','k14','','Time to Peak Torque (Seconds)','','1','lhj'),
('30','TimePeakTorqueHeld','k15','','Time Peak Torque Held (Seconds)','','1','lhj'),
('30','ForceDecayTime','k16','','Force Decay Time (Seconds)','','1','lhj'),
('30','ReciprocalDelay','k17','','Reciprocal Delay (Seconds)','','1','lhj'),
('30','DelayTime','k18','','Delay Time (Seconds)','','1','lhj'),
('30','yuliu1','k19','','yuliu1','','0','lhj'),
('30','yuliu2','k20','','yuliu2','','0','lhj'),
('30','Key','k21','','Key','','0','lhj'),
('30','ProtocolRowKey','k22','','ProtocolRowKey','','0','lhj'),
('30','Inv','k23','','Inv','','0','lhj'),
('30','Dom','k24','','Dom','','0','lhj'),
('30','AvgTrq','k25','','Average Torque','','0','lhj'),
('30','AvgTrqBW','k26','','Average Torque to Body Weight Ratio','','0','lhj'),
('30','AvgTrqDeficit','k27','','Involved/Uninvolved Average Torque Deficit','','0','lhj'),
('30','AvgTrqRatio','k28','','Reciprocal/Initial Average Torque Ratio','','0','lhj'),
('30','AvgVelocity','k29','','Average Velocity','','0','lhj'),
('30','AvgVelocity_bw','k30','','Average Velocity to Body Weight Ratio','','0','lhj'),
('30','AvgVelocity_deficit','k31','','Involved/Uninvolved Average Velocity Deficit','','0','lhj'),
('30','AvgVelocity_ratio','k32','','Reciprocal/Initial Average Velocity Ratio','','0','lhj'),
('30','CoeffOfVar','k33','','Coefficent of Variation between Target and Actual','','0','lhj'),
('30','CoeffOfVarNoFeedback','k34','','Proprioception: Coefficent of Variation between Target and Actual without Visual Feedback','','0','lhj'),
('30','DirectionalControlActual','k35','','Acutal Distance Travelled by Patient','','0','lhj'),
('30','DirectionalControlMin','k36','','Minimum Distanct to Target','','0','lhj'),
('30','DirectionalControlRatio','k37','','Min/Actual Ratio','','0','lhj'),
('30','DirectionalControlTime','k38','','Min/Actual Ratio','','0','lhj'),
('30','dt','k39','','Delay Time','','0','lhj'),
('30','EllipseMajorRadius','k40','','95% Ellipse Radius','','0','lhj'),
('30','EllipseMinorRadius','k41','','95% Ellipse Radius','','0','lhj'),
('30','EllipseRotation','k42','','95% Ellipse Rotation','','0','lhj'),
('30','EllipseX0','k43','','95% Ellipse Center','','0','lhj'),
('30','EllipseY0','k44','','95% Ellipse Center','','0','lhj'),
('30','EnvelopeAngle','k45','','Stability Envelope Angle','','0','lhj'),
('30','EnvelopeArea','k46','','Stability Envelope Area','','0','lhj'),
('30','EnvelopeLength','k47','','Stability Envelope Length','','0','lhj'),
('30','fdt','k48','','Force Decay Time','','0','lhj'),
('30','InitialPeakPower','k49','','Initial Peak Velocity first 3 reps) on Endurance Test','','0','lhj'),
('30','InitialPeakPower_bw','k50','','Initial Peak Velocity to Body Weight Ratio','','0','lhj'),
('30','InitialPeakPower_deficit','k51','','Involved/Uninvolved Initial Peak Velocity Deficit','','0','lhj'),
('30','InitialPeakPower_ratio','k52','','Reciprocal/Initial Initial Peak Velocity Ratio','','0','lhj'),
('30','InitialPeakTorque','k53','','Initial Peak Torque (first 3 reps) on Endurance Test','','0','lhj'),
('30','InitialPeakTorque_bw','k54','','Initial Peak Torque to Body Weight Ratio','','0','lhj'),
('30','InitialPeakTorque_deficit','k55','','Involved/Uninvolved Initial Peak Torque Deficit','','0','lhj'),
('30','InitialPeakTorque_ratio','k56','','Reciprocal/Initial Initial Peak Torque Ratio','','0','lhj'),
('30','InitialPeakVelocity','k57','','Initial Peak Velocity (first 3 reps) on Endurance Test','','0','lhj'),
('30','InitialPeakVelocity_bw','k58','','Initial Peak Velocity to Body Weight Ratio','','0','lhj'),
('30','InitialPeakVelocity_deficit','k59','','Involved/Uninvolved Initial Peak Velocity Deficit','','0','lhj'),
('30','InitialPeakVelocity_ratio','k60','','Reciprocal/Initial Initial Peak Velocity Ratio','','0','lhj'),
('30','intAction','k61','','Dyna Action: 0:Con/Con 1:Con/Ecc 2:Ecc/Con 3:Ecc/Ecc','','0','lhj'),
('30','intMode','k62','','Dyna Mode: 0:IsoK 1:CPM 2:IsoM  3:IsoT','','0','lhj'),
('30','japp','k63','','Joint Angle at Peak Velocity','','0','lhj'),
('30','japt','k64','','Joint Angle at Peak Torque','','0','lhj'),
('30','japv','k65','','Joint Angle at Peak Velocity','','0','lhj'),
('30','MaxDeviation','k66','','Maximum Deviation between Target and Actual','','0','lhj'),
('30','MaxDeviationNoFeedback','k67','','Proprioception: Maximum Deviation between Target and Actual without Visual Feedback','','0','lhj'),
('30','Motion','k68','','0: Initial Motion  1: Reciprocal Motion','','0','lhj'),
('30','p_deficit','k69','','Involved/Uninvolved Power Deficit','','0','lhj'),
('30','p_fatigue','k70','','Initial Peak Velocity Fatigue Index','','0','lhj'),
('30','p_ratio','k71','','Reciprocal/Initial Power Ratio','','0','lhj'),
('30','PathLength','k72','','Path Length Traveled','','0','lhj'),
('30','PctOnTarget','k73','','Interactive Line/Path: Percent on target','','0','lhj'),
('30','pdt','k74','','Velocity Decay Time','','0','lhj'),
('30','PeakPower','k75','','Peak Power','','0','lhj'),
('30','PeakPower_bw','k76','','Peak Power to Body Weight Ratio','','0','lhj'),
('30','PeakPower_deficit','k77','','Involved/Uninvolved Peak Power Deficit','','0','lhj'),
('30','PeakPower_ratio','k78','','Reciprocal/Initial Peak Power Ratio','','0','lhj'),
('30','PeakTrqSlope','k79','','Peak Torque/Time To Peak Torque','','0','lhj'),
('30','PeakTrqSlopeBW','k80','','Peak Torque Slope to Body Weight Ratio','','0','lhj'),
('30','PeakTrqSlopeDeficit','k81','','Involved/Uninvolved Peak Torque Slope Deficit','','0','lhj'),
('30','PeakTrqSlopeRatio','k82','','Reciprocal/Initial Peak Torque Slope Ratio','','0','lhj'),
('30','PeakVelocity','k83','','Peak Velocity','','0','lhj'),
('30','PeakVelocity_bw','k84','','Peak Velocity to Body Weight Ratio','','0','lhj'),
('30','PeakVelocity_deficit','k85','','Involved/Uninvolved Peak Velocity Deficit','','0','lhj'),
('30','PeakVelocity_ratio','k86','','Reciprocal/Initial Peak Velocity Ratio','','0','lhj'),
('30','power','k87','','Power (Computed over Complete Repetition)','','0','lhj'),
('30','power_bw','k88','','Power to Body Weight Ratio','','0','lhj'),
('30','pt','k89','','Peak Torque','','0','lhj'),
('30','pt_bw','k90','','Peak Torque to Body Weight Ratio','','0','lhj'),
('30','rd','k91','','Reciprocal Delay','','0','lhj'),
('30','ReactionTime','k92','','Response Time Test: Reaction Time','','0','lhj'),
('30','rom','k93','','Position at Range of Motion Limit','','0','lhj'),
('30','RowNbr','k94','','The Set in the Protocol with 0 being the first set.','','0','lhj'),
('30','SDX','k95','','Std Dev of X','','0','lhj'),
('30','SDXY','k96','','Std Dev of (X  Y)','','0','lhj'),
('30','SDY','k97','','Std Dev of Y','','0','lhj'),
('30','Seq','k98','','The Repetition  Motion pair. 0: First Rep  Initial Motion.1: First Rep Recip Motion. 2: Second Rep  Initial Motion','','0','lhj'),
('30','SettingInit','k99','','Dyna Init Motion setting. Isokinetic CPM:Speed  Isotonic:Torque Isometric:Angle.','','0','lhj'),
('30','SettingRecip','k100','','Dyna Recip Motion setting. Isokinetic  CPM:Speed  Isotonic:Torque Isometric:Hold Time.','','0','lhj'),
('30','SettleTime','k101','','Response Time Test: Time to Settle in Target','','0','lhj'),
('30','Side','k102','','0: Right Side  1: Left Side','','0','lhj'),
('30','StabilityIndexCombined','k103','','Mean Distance from Origin','','0','lhj'),
('30','StabilityIndexX','k104','','Mean Distance from Origin in X Axis','','0','lhj'),
('30','StabilityIndexY','k105','','Mean Distance from Origin in Y Axis','','0','lhj'),
('30','StabilityScore','k106','','95% Stability Score vs. NORMS','','0','lhj'),
('30','Stat','k107','','0: Average Value  1: Coeff of Var','','0','lhj'),
('30','SwayIndex','k108','','Standard Deviation of all Point','','0','lhj'),
('30','t_deficit','k109','','Involved/Uninvolved Torque Deficit','','0','lhj'),
('30','t_fatigue','k110','','Initial Peak Torque Fatigue Index','','0','lhj'),
('30','t_ratio','k111','','Reciprocal/Initial Torque Ratio','','0','lhj'),
('30','TestRunningTime','k112','','Time in seconds for complete exercise.','','0','lhj'),
('30','TimeToHalfPeakTrq','k113','','Time to Half Peak Torque','','0','lhj'),
('30','TotalMotionTime','k114','','Time to Move Through Complete Motion (PS to PE)','','0','lhj'),
('30','TotalWork','k115','','Total Work (Sum of all repetition)','','0','lhj'),
('30','TotalWork_bw','k116','','Total Work to Body Weight Ratio','','0','lhj'),
('30','TotalWork_deficit','k117','','Involved/Uninvolved Total Work Deficit','','0','lhj'),
('30','TotalWork_ratio','k118','','Reciprocal/Initial Total Work Ratio','','0','lhj'),
('30','tpph','k119','','Time Peak Velocity Held','','0','lhj'),
('30','tpth','k120','','Time Peak Torque Held','','0','lhj'),
('30','tpvh','k121','','Time Peak Velocity Held','','0','lhj'),
('30','ttpp','k122','','Time to Peak Velocity','','0','lhj'),
('30','ttpt','k123','','Time to Peak Torque','','0','lhj'),
('30','ttpv','k124','','Time to Peak Velocity','','0','lhj'),
('30','v_fatigue','k125','','Initial Peak Velocity Fatigue Index','','0','lhj'),
('30','vdt','k126','','Velocity Decay Time','','0','lhj'),
('30','w_deficit','k127','','Involved/Uninvolved Work Deficit','','0','lhj'),
('30','w_fatigue','k128','','Endurance Ratio','','0','lhj'),
('30','w_ratio','k129','','Reciprocal/Initial Work Ratio','','0','lhj'),
('30','work','k130','','Work (Per Repetition)','','0','lhj'),
('30','work_bw','k131','','Work to Body Weight Ratio','','0','lhj');

-- footscan结果数据 2023-03-26
insert into ydy_equipment_relation_dict(type,note,is_del,create_time,update_time,create_by) values
(34,'footscan结果数据',0,now(),now(),'兰海军');
-- footscan过程数据 2023-03-26
insert into ydy_equipment_relation_dict(type,note,is_del,create_time,update_time,create_by) values
(35,'footscanProcess',0,now(),now(),'兰海军');

insert into ydy_equipment_relation(type,k,v,note,note_en,unit,upper_limit,lower_limit,is_norm,create_by)
values 
('34','footAxisLeft','k1','足轴角-左','Foot axis  Left','°','12','5','1','兰海军'),
('34','footAxisRight','k2','足轴角-右','Foot axis  Right','°','12','5','1','兰海军'),
('34','subtalarJointFlexibilityLeft','k3','距下关节活动度-左','Subtalar joint flexibility Left','°','25','10','1','兰海军'),
('34','subtalarJointFlexibilityRight','k4','距下关节活动度-右','Subtalar joint flexibility Right','°','25','10','1','兰海军'),
('34','surfaceMidfootLeft','k5','足弓指数-左','Surface midfoot Left','%','28','21','1','兰海军'),
('34','surfaceMidfootRight','k6','足弓指数-右','Surface midfoot Right','%','28','21','1','兰海军'),
('34','pressureGraphsCursorsLeft','k7','最大受力位置-左','Pressure (N/cm2) graphs cursors Left','','','','1','兰海军'),
('34','pressureGraphsCursorsRight','k8','最大受力位置-右','Pressure (N/cm2) graphs cursors Right','','','','1','兰海军'),
('34','firstFrameAppearAreaLeft','k9','第一帧出现区域-左','First Frame appear Area left','','','','1','兰海军'),
('34','firstFrameAppearAreaRight','k10','第一帧出现区域-右','First Frame appear Area right','','','','1','兰海军'),
('34','lastFootContactLeft','k11','支撑期时间-左','last foot contact left','ms','800','600','1','兰海军'),
('34','lastFootContactRight','k12','支撑期时间-右','last foot contact right','ms','800','600','1','兰海军'),
('34','COPTraveledDistance','k13','压力中心移动距离','COP traveled distance (mm)','mm','','','1','兰海军');


-- 2024-05-09omegawave
INSERT INTO `ydy_equipment_relation_dict` (`type`, `note`, `is_del`, `create_time`, `update_time`, `create_by`) VALUES
(40, 'Omega wave竟技状态综合诊断系统-(便携式设备)', 0, now(), now(), '兰海军');

alter table `ydy_equipment_relation` change column `k` `k` varchar(64) NOT NULL DEFAULT '' COMMENT '设备参数真实列名';

INSERT INTO `ydy_equipment_relation` (`type`, `k`, `v`, `note`, `note_en`, `is_norm`, `create_by`) VALUES
(40, 'GUID', 'k1', 'GUID', 'GUID', 0, '兰海军'),
(40, 'index-OverallReadiness', 'k2', 'Overall Readiness', 'Overall Readiness', 1, '兰海军'),
(40, 'index-GenesisHr', 'k3', 'Resting Heart Rate', 'Resting Heart Rate', 1, '兰海军'),
(40, 'index-GenesisAnaerobicDevelopment', 'k4', 'Z6 – Anaerobic development', 'Z6 – Anaerobic development', 1, '兰海军'),
(40, 'index-GenesisAnaerobicMaintenance', 'k5', 'Z5 – Anaerobic maintenance', 'Z5 – Anaerobic maintenance', 1, '兰海军'),
(40, 'index-GenesisAerobicDevelopment', 'k6', 'Z4 – Aerobic development', 'Z4 – Aerobic development', 1, '兰海军'),
(40, 'index-GenesisAerobicMaintenance', 'k7', 'Z3 – Aerobic maintenance', 'Z3 – Aerobic maintenance', 1, '兰海军'),
(40, 'index-GenesisRecoveryStimulation', 'k8', 'Z2 - Recovery stimulation', 'Z2 - Recovery stimulation', 1, '兰海军'),
(40, 'index-GenesisRecuperation', 'k9', 'Z1 - Recuperation', 'Z1 - Recuperation', 1, '兰海军'),
(40, 'index-GenesisCNSReadiness', 'k10', 'Central Nervous System Readiness', 'Central Nervous System Readiness', 1, '兰海军'),
(40, 'index-CNSLevelOfActivation', 'k11', 'DC Potential', 'DC Potential', 1, '兰海军'),
(40, 'index-CardiacReadiness', 'k12', 'Cardiac System System Readiness', 'Cardiac System System Readiness', 1, '兰海军'),
(40, 'index-GenesisRecoveryPattern', 'k13', 'Recovery Pattern', 'Recovery Pattern', 1, '兰海军'),
(40, 'index-GenesisAdaptationReservesGrade', 'k14', 'Adaptation reserves', 'Adaptation reserves', 1, '兰海军'),
(40, 'index-GenesisCardiacStress', 'k15', 'Stress', 'Stress', 1, '兰海军'),
(40, 'index-GenesisCRI', 'k16', 'Parasympathetic activity (s)', 'Parasympathetic activity (s)', 1, '兰海军'),
(40, 'index-GenesisAMO', 'k17', 'Sympathetic activity (%)', 'Sympathetic activity (%)', 1, '兰海军'),
(40, 'index-GenesisTi', 'k18', 'Level of tension (r.u.)', 'Level of tension (r.u.)', 1, '兰海军'),
(40, 'index-GenesisAB', 'k19', 'Aperiodic influences (s)', 'Aperiodic influences (s)', 1, '兰海军'),
(40, 'index-GenesisddSigmaBWave', 'k20', 'Aspirate waves (r.u.)', 'Aspirate waves (r.u.)', 1, '兰海军'),
(40, 'index-GenesisSDNN', 'k21', 'SDNN (ms)', 'SDNN (ms)', 1, '兰海军'),
(40, 'index-GenesisSDSD', 'k22', 'SDSD (ms)', 'SDSD (ms)', 1, '兰海军'),
(40, 'index-GenesisRMSSD', 'k23', 'RMSSD (ms)', 'RMSSD (ms)', 1, '兰海军'),
(40, 'index-GenesisTotalPower', 'k24', 'Total power (ms²)', 'Total power (ms²)', 1, '兰海军'),
(40, 'index-GenesisLFdifHF', 'k25', 'LF/HF', 'LF/HF', 1, '兰海军'),
(40, 'index-GenesisHF', 'k26', 'HF (ms²)', 'HF (ms²)', 1, '兰海军'),
(40, 'index-GenesisHFNorm', 'k27', 'HF n.u. (n.u.)', 'HF n.u. (n.u.)', 1, '兰海军'),
(40, 'index-GenesisLF', 'k28', 'LF (ms²)', 'LF (ms²)', 1, '兰海军'),
(40, 'index-GenesisLFNorm', 'k29', 'LF n.u. (n.u.)', 'LF n.u. (n.u.)', 1, '兰海军'),
(40, 'index-GenesisMRIGrade', 'k30', 'Energy Supply System Readiness', 'Energy Supply System Readiness', 1, '兰海军'),
(40, 'index-GenesisMRI', 'k31', 'MRI', 'MRI', 1, '兰海军'),
(40, 'index-GenesisASI', 'k32', 'Aerobic Readiness', 'Aerobic Readiness', 1, '兰海军'),
(40, 'index-GenesisANSI', 'k33', 'Anaerobic Readiness', 'Anaerobic Readiness', 1, '兰海军'),
(40, 'SubjectGUID', 'k34', 'SubjectGUID', 'SubjectGUID', 0, '兰海军'),
(40, 'AssessmentDateTimeUTC', 'k35', 'AssessmentDateTimeUTC', 'AssessmentDateTimeUTC', 0, '兰海军'),
(40, 'AssessmentDateTimeLocalTime', 'k36', 'AssessmentDateTimeLocalTime', 'AssessmentDateTimeLocalTime', 0, '兰海军'),
(40, 'FirstName', 'k37', 'FirstName', 'FirstName', 0, '兰海军'),
(40, 'LastName', 'k38', 'LastName', 'LastName', 0, '兰海军'),
(40, 'CalculationStatus', 'k39', 'CalculationStatus', 'CalculationStatus', 0, '兰海军'),
(40, 'Modified', 'k40', 'Modified', 'Modified', 0, '兰海军'),
(40, 'Tags', 'k41', 'Tags', 'Tags', 0, '兰海军'),
(40, 'index-AssessmentInvalidationReason', 'k42', 'index-AssessmentInvalidationReason', 'index-AssessmentInvalidationReason', 0, '兰海军'),
(40, 'index-CalculationVersionMain', 'k43', 'index-CalculationVersionMain', 'index-CalculationVersionMain', 0, '兰海军'),
(40, 'index-DCCurveGrade', 'k44', 'index-DCCurveGrade', 'index-DCCurveGrade', 0, '兰海军'),
(40, 'index-DCStabilizationLevelGrade', 'k45', 'index-DCStabilizationLevelGrade', 'index-DCStabilizationLevelGrade', 0, '兰海军'),
(40, 'index-DCStabilizationLevelMv', 'k46', 'index-DCStabilizationLevelMv', 'index-DCStabilizationLevelMv', 0, '兰海军'),
(40, 'index-DCStabilizationTimeInSeconds', 'k47', 'index-DCStabilizationTimeInSeconds', 'index-DCStabilizationTimeInSeconds', 0, '兰海军'),
(40, 'index-DCTensionExhaustionLevel', 'k48', 'index-DCTensionExhaustionLevel', 'index-DCTensionExhaustionLevel', 0, '兰海军'),
(40, 'index-DCTimeGradeReduction', 'k49', 'index-DCTimeGradeReduction', 'index-DCTimeGradeReduction', 0, '兰海军'),
(40, 'index-EnduranceReadiness', 'k50', 'index-EnduranceReadiness', 'index-EnduranceReadiness', 0, '兰海军'),
(40, 'index-GenesisCNS', 'k51', 'index-GenesisCNS', 'index-GenesisCNS', 0, '兰海军'),
(40, 'index-GenesisDX1', 'k52', 'index-GenesisDX1', 'index-GenesisDX1', 0, '兰海军'),
(40, 'index-GenesisHighArrythmia', 'k53', 'index-GenesisHighArrythmia', 'index-GenesisHighArrythmia', 0, '兰海军'),
(40, 'index-GenesisHR_AN', 'k54', 'index-GenesisHR_AN', 'index-GenesisHR_AN', 0, '兰海军'),
(40, 'index-GenesisIncreaseOfCardiacOutput', 'k55', 'index-GenesisIncreaseOfCardiacOutput', 'index-GenesisIncreaseOfCardiacOutput', 0, '兰海军'),
(40, 'index-GenesisMaximumTraingingHeartRate', 'k56', 'index-GenesisMaximumTraingingHeartRate', 'index-GenesisMaximumTraingingHeartRate', 0, '兰海军'),
(40, 'index-GenesisMO', 'k57', 'index-GenesisMO', 'index-GenesisMO', 0, '兰海军'),
(40, 'index-GenesisOmegaBase', 'k58', 'index-GenesisOmegaBase', 'index-GenesisOmegaBase', 0, '兰海军'),
(40, 'index-GenesisPNS', 'k59', 'index-GenesisPNS', 'index-GenesisPNS', 0, '兰海军'),
(40, 'index-GenesisPulse', 'k60', 'index-GenesisPulse', 'index-GenesisPulse', 0, '兰海军'),
(40, 'index-GenesisRank1', 'k61', 'index-GenesisRank1', 'index-GenesisRank1', 0, '兰海军'),
(40, 'index-GenesisRank2', 'k62', 'index-GenesisRank2', 'index-GenesisRank2', 0, '兰海军'),
(40, 'index-GenesisRank3', 'k63', 'index-GenesisRank3', 'index-GenesisRank3', 0, '兰海军'),
(40, 'index-GenesisRank4', 'k64', 'index-GenesisRank4', 'index-GenesisRank4', 0, '兰海军'),
(40, 'index-GenesisRank5', 'k65', 'index-GenesisRank5', 'index-GenesisRank5', 0, '兰海军'),
(40, 'index-GenesisRank6', 'k66', 'index-GenesisRank6', 'index-GenesisRank6', 0, '兰海军'),
(40, 'index-GenesisRecomendationIndex', 'k67', 'index-GenesisRecomendationIndex', 'index-GenesisRecomendationIndex', 0, '兰海军'),
(40, 'index-GenesisRecoveryEfficiency', 'k68', 'index-GenesisRecoveryEfficiency', 'index-GenesisRecoveryEfficiency', 0, '兰海军'),
(40, 'index-GenesisReservesGrade', 'k69', 'index-GenesisReservesGrade', 'index-GenesisReservesGrade', 0, '兰海军'),
(40, 'index-GenesisReservesStr', 'k70', 'index-GenesisReservesStr', 'index-GenesisReservesStr', 0, '兰海军'),
(40, 'index-GenesisRhythmDisturbancesStr', 'k71', 'index-GenesisRhythmDisturbancesStr', 'index-GenesisRhythmDisturbancesStr', 0, '兰海军'),
(40, 'index-GenesisSNS', 'k72', 'index-GenesisSNS', 'index-GenesisSNS', 0, '兰海军'),
(40, 'index-GenesisStressIndexGrade', 'k73', 'index-GenesisStressIndexGrade', 'index-GenesisStressIndexGrade', 0, '兰海军'),
(40, 'index-GenesisStressIndexStr', 'k74', 'index-GenesisStressIndexStr', 'index-GenesisStressIndexStr', 0, '兰海军'),
(40, 'index-GenesisString1', 'k75', 'index-GenesisString1', 'index-GenesisString1', 0, '兰海军'),
(40, 'index-GenesisTirednessGrade', 'k76', 'index-GenesisTirednessGrade', 'index-GenesisTirednessGrade', 0, '兰海军'),
(40, 'index-GenesisTirednessStr', 'k77', 'index-GenesisTirednessStr', 'index-GenesisTirednessStr', 0, '兰海军'),
(40, 'index-GenesisVLF', 'k78', 'index-GenesisVLF', 'index-GenesisVLF', 0, '兰海军'),
(40, 'index-MaximumTrainingZone', 'k79', 'index-MaximumTrainingZone', 'index-MaximumTrainingZone', 0, '兰海军'),
(40, 'index-OverallDC', 'k80', 'index-OverallDC', 'index-OverallDC', 0, '兰海军'),
(40, 'index-OverallReadinessAccurate', 'k81', 'index-OverallReadinessAccurate', 'index-OverallReadinessAccurate', 0, '兰海军'),
(40, 'index-RestingHR', 'k82', 'index-RestingHR', 'index-RestingHR', 0, '兰海军'),
(40, 'index-SkillWorkReadiness', 'k83', 'index-SkillWorkReadiness', 'index-SkillWorkReadiness', 0, '兰海军'),
(40, 'index-SpeedAndPowerReadiness', 'k84', 'index-SpeedAndPowerReadiness', 'index-SpeedAndPowerReadiness', 0, '兰海军'),
(40, 'index-StrengthReadiness', 'k85', 'index-StrengthReadiness', 'index-StrengthReadiness', 0, '兰海军'),
(40, 'index-WoTRecommendationTextIndex', 'k86', 'index-WoTRecommendationTextIndex', 'index-WoTRecommendationTextIndex', 0, '兰海军'),
(40, 'index-WoTStateTextIndex', 'k87', 'index-WoTStateTextIndex', 'index-WoTStateTextIndex', 0, '兰海军');